### PR TITLE
LPS-67504 Update API template bundle version

### PR DESCRIPTION
**Pull request by dnebing**
LPS-67504 This has an updated bundle version for the core template bundle

### CODE REVIEW

**Comment by lawrence-lee** [comment]
test this please

**Comment by dnebing** [comment]
It is tested but it depends upon the other PR to liferay-portal with the updated gradle templates, needs 1.0.18 and it's not available yet.

**Comment by lawrence-lee** [comment]
Hi @dnebing, Sorry for the mix up. "Test this please" is the trigger phrase for my CI to run the tests. I'm changing it to CI:Retest to avoid future confusion.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-cli/pull/120. [See changes here.](https://github.com/gamerson/liferay-blade-cli/compare/b0b714c~1...b0b714c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
