### PR TITLE
support creating maven type projects

### PR DESCRIPTION
**Pull request by AndyWu2015**
I just changed four junit tests for maven , if you are ok with the code, I will full fill the other junit tests.

### CODE REVIEW

**Comment by gamerson** [comment]
@AndyWu2015  MavenRunnerUtil is failing on Windows, see here: http://cloud-10-50-0-254/job/liferay-blade-cli-pr-tester/96/testReport/  Can you take a look?

**Comment by AndyWu2015** [comment]
ok. I will take a look

**Comment by gamerson** [comment]
jenkins retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/AndyWu2015/liferay-blade-cli/pull/4. [See changes here.](https://github.com/gamerson/liferay-blade-cli/compare/d4ae621~3...d4ae621) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
