### PR TITLE
[Migrator] Renamed Packages to Fix the Split Packages Problem

### PR DESCRIPTION
**Pull request by lovettli**

### CODE REVIEW

**Comment by gamerson** [comment]
@lovettli see failling test here: https://liferay-test-01.ci.cloudbees.com/job/liferay-blade-cli-pr-tester/121/testReport/

**Comment by lovettli** [comment]
Have updated.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/lovettli/liferay-blade-cli/pull/1. [See changes here.](https://github.com/gamerson/liferay-blade-cli/compare/2525e64~2...2525e64) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
