### PR TITLE
support target platform for blade

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
ci:retest

**Comment by jtydhr88** [comment]
@haoyisun can you check the failure tests?

**Comment by gamerson** [comment]
thanks @haoyisun  for starting this PR.  I'll fix up the tests today

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-cli/pull/493. [See changes here.](https://github.com/gamerson/liferay-blade-cli/compare/156ae84a~8...156ae84a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
