### PR TITLE
BLADE-305

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
@gamerson Can you take a look at the last post? https://github.com/gamerson/liferay-blade-cli/pull/537#issuecomment-423390760

I force pushed so the commits and comments are messed up. Once you merge, i'm going to push this change to the other servers.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-cli/pull/541. [See changes here.](https://github.com/gamerson/liferay-blade-cli/compare/cb9ee57d~3...cb9ee57d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
