### PR TITLE
BLADE-276 Fix blade init .

### PR DESCRIPTION
**Pull request by christopherbryanboyd**

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:test

**Comment by christopherbryanboyd** [comment]
ci:test

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-cli/pull/494. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
