### PR TITLE
340changelog

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
@gamerson, please hold off until we can figure out what's going on with the appveyor test failure

**Comment by christopherbryanboyd** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
@gamerson This looks good. I think we're ready for `3.4.1`

**Comment by gamerson** [comment]
@lawrence-lee pushed!

**Pull request merged**
