### PR TITLE
Design cache way

### PR DESCRIPTION
**Pull request by jtydhr88**

### CODE REVIEW

**Comment by jtydhr88** [comment]
Hey @gamerson I changed the way of Cache, made the CUCache  as OSGi bundle and add CacheUtil in the api bundle. as the this reason, our api changes tests can't run as normal junit test, I move all of them to blade.test bundle

**Comment by jtydhr88** [comment]
Please review when you are free, as this one relates to a serious UI bug in Code upgrade tool.

**Comment by gamerson** [comment]
Hey Terry why did you need to move the cache util into osgi DS?

**Comment by jtydhr88** [comment]
Hey as when we do the auto correct but we don't remove the ast cache from cache map, it will cause  when we re-find on the file, it find the wrong code although we have fixed this problem.
Now the  autocorrect of  ImportStatementMigrator in liferay70 bundle but the cache map in the eclipse.provider bundle, I don't liferay 70 should refer to eclipse.provider bundle, so I created that Osgi DS

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/jtydhr88/liferay-blade-cli/pull/2. [See changes here.](https://github.com/gamerson/liferay-blade-cli/compare/86ec6cb~1...86ec6cb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
