### PR TITLE
BLADE-316 Add new function and command for blade server

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:retest

**Comment by simonjhy** [comment]
ci:retest

**Comment by simonjhy** [comment]
Hi greg, I checked windows jenkins test. Its seems it was not very stable. The latest two tests are not really started successfully at all.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Hey @simonjhy 

I have recently refactored the server commands.  I'm sorry to have to ask you to rebase this, but can you give it a try?  Let me know ifyou have any questions.

**Pull request closed without merging**
