### PR TITLE
BLADE-250 Interactive

### PR DESCRIPTION
**Pull request by christopherbryanboyd**

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-cli/pull/439. [See changes here.](https://github.com/gamerson/liferay-blade-cli/compare/a2b398a~12...a2b398a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
