### PR TITLE
TEST COMMIT DO NOT MERGE

### PR DESCRIPTION
**Pull request by christopherbryanboyd**

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
It looks like we don't have a build scan for the Windows failure, is something wrong with the Windows CI?

**Comment by lawrence-lee** [comment]
https://gist.github.com/lawrence-lee/518eb574dbeef6691fa1cebe07691a90
@christopherbryanboyd , has this been happening for multiple builds? If so, we might need to reboot the thing.

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Pull request closed without merging**
