### PR TITLE
 BLADE-250 interactive 

### PR DESCRIPTION
**Pull request by christopherbryanboyd**

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by gamerson** [comment]
please rebase and resend, thanks!

**Comment by christopherbryanboyd** [comment]
Hi @gamerson , this has been resent here https://github.com/gamerson/liferay-blade-cli/pull/427/

**Pull request closed without merging**
