### PR TITLE
update gradle-tooling-api to 2.14

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Please resend, thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
@AndyWu2015 compile error please resend.  thanks!

**Comment by AndyWu2015** [comment]
it seems gradle-tooling-api 2.14 removed lots of API classes.  searching

**Comment by AndyWu2015** [comment]
never mind , we just use gradle-tooling-api-2.13.jar is ok

**Comment by gamerson** [comment]
I'm fine with moving to 2.14.  But we just need to update our code to
support it right?

On Mon, Jul 4, 2016 at 1:09 AM, Andy Wu <notifications@github.com> wrote:

> never mind , we just use gradle-tooling-api-2.13.jar is ok
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/gamerson/liferay-blade-cli/pull/71#issuecomment-230212358>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAkVFQAkL9l-qbnwmNzdkwNKOP-YvCkMks5qSKOmgaJpZM4JCw09>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request closed without merging**
