### PR TITLE
fix initCommand and tests

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
CI:Retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
I got the same error when running the test locally.

**Comment by AndyWu2015** [comment]
ok I will take a look.

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-cli/pull/130. [See changes here.](https://github.com/gamerson/liferay-blade-cli/compare/ba3c7ff~1...ba3c7ff) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
