### PR TITLE
BLADE-216: Fix samples command to use latest samples

### PR DESCRIPTION
**Pull request by christopherbryanboyd**
Addresses https://issues.liferay.com/projects/BLADE/issues/BLADE-216 _**Generating Blade Samples with Blade CLI is outdated and broken**_

### CODE REVIEW

**Comment by gamerson** [comment]
hey @christopherbryanboyd  can you take a look at the failing windows test?

**Comment by gamerson** [comment]
hey @christopherbryanboyd can you rebase on master and resend?  thanks

**Comment by wodencafe** [comment]
Hey @gamerson , no problem, the updated PR has been sent here: https://github.com/gamerson/liferay-blade-cli/pull/345

**Comment by christopherbryanboyd** [comment]
Hey @gamerson , no problem, the updated PR has been sent here: #345

**Pull request closed without merging**
