### PR TITLE
update check for empty directory

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
jenkins retest

**Comment by lawrence-lee** [comment]
errors from windows console 
```
com.liferay.blade.upgrade.liferay70.apichanges.DDMLegacyAPITest > dDMLegacyAPITest FAILED
    java.lang.AssertionError: expected:<4829> but was:<4832>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at com.liferay.blade.upgrade.liferay70.apichanges.DDMLegacyAPITest.dDMLegacyAPITest(DDMLegacyAPITest.java:71)

com.liferay.blade.upgrade.liferay70.apichanges.MBMessageServiceUtilInvocationTest > dlAppHelperLocalServiceTest FAILED
    java.lang.AssertionError: expected:<8077> but was:<8078>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at com.liferay.blade.upgrade.liferay70.apichanges.MBMessageServiceUtilInvocationTest.dlAppHelperLocalServiceTest(MBMessageServiceUtilInvocationTest.java:57)
```

**Pull request closed without merging**
