### PR TITLE
BLADE-383 Fix unwanted stack traces

### PR DESCRIPTION
**Pull request by christopherbryanboyd**
Hi @gamerson , this addresses https://issues.liferay.com/browse/BLADE-383

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:stop

**Comment by christopherbryanboyd** [comment]
ci:skip

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-cli/pull/709. [See changes here.](https://github.com/gamerson/liferay-blade-cli/compare/6517b862~2...6517b862) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
