### PR TITLE
BLADE-552 Check that blade create points to a path inside Liferay Workspace

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @Seiphon  can you take a look at the errors?  I'm going to send this PR back to you.

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/Seiphon/liferay-blade-cli/pull/1. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/simonjhy/liferay-blade-cli/pull/14. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Seiphon** [comment]
Hi @gamerson ，I will work on this pr to solve these test faliures on weekend when I back to Dalian.

**Pull request closed without merging**
