### PR TITLE
LPS-114909 Fix maven standalone test

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by gamerson** [comment]
hey lawrence, I've added my own fixes here: https://github.com/gamerson/liferay-blade-cli/pull/1051

**Comment by gamerson** [comment]
but i see you have also fixed a maven standalone
i could incorporate your fix in mine.

**Comment by lawrence-lee** [comment]
Yea You can just cherry pick these two commits and close this out

**Comment by gamerson** [comment]
I've added your fixes here: https://github.com/gamerson/liferay-blade-cli/pull/1051

**Pull request closed without merging**
