### PR TITLE
correct imports in ContactNameExceptionImport

### PR DESCRIPTION
**Pull request by AndyWu2015**
as the exceptions are moved to inner classes , we should just import the public class .
imports

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See 216e295...9872dfa <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
@AndyWu2015 you know what we really need... is a Unit Test for the AutoCorrect.  But we can add that later.

**Comment by AndyWu2015** [comment]
oo got it.

**Comment by AndyWu2015** [comment]
I think we could not test AutoCorrect  in normal junit test .

**Pull request closed without merging**
