### PR TITLE
BLADE-554 Semver

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @lawrence-lee   could you take a look at the failed tests here? 
https://scans.gradle.com/s/lmor5zprjqgei

**Comment by lawrence-lee** [comment]
@gamerson, this looks okay to me

**Comment by lawrence-lee** [comment]
I'm not sure how we broke the smoke tests in windows

**Comment by gamerson** [comment]
The smoke tests on windows has something to do with the nodejs modules that are invoked by the js-widget/js-theme templates.  I think Dave was going to try to replicate on a windows VM.

**Pull request merged**
