### PR TITLE
BLADE-190: blade to support deploying wars to Liferay

### PR DESCRIPTION
**Pull request by christopherbryanboyd**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @christopherbryanboyd  looks like this one is going to need rebase now.  sorry about that.

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci test

**Comment by gamerson** [comment]
nice job getting it working, can you rebase and resend?  thanks!

**Comment by christopherbryanboyd** [comment]
Hey @gamerson, I rebased and resent here https://github.com/gamerson/liferay-blade-cli/pull/331 :smile:

**Pull request closed without merging**
