### PR TITLE
Refactor and fix tests

### PR DESCRIPTION
**Pull request by christopherbryanboyd**

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
Phew, @gamerson I think this one is finally ready for review.

**Comment by gamerson** [comment]
hey @christopherbryanboyd  can squash and rebase and re add a commit that includes a BLADE-123 style ticket header?  Also you may need to create a new BLADE ticket that covers this work.  Thanks

**Comment by christopherbryanboyd** [comment]
Hey, submitted here :) https://github.com/gamerson/liferay-blade-cli/pull/459

**Pull request closed without merging**
