### PR TITLE
Use Java Standard Library for reading InputStreams

### PR DESCRIPTION
**Pull request by christopherbryanboyd**

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by christopherbryanboyd** [comment]
ci:retest

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/liferay-blade-cli/pull/440. [See changes here.](https://github.com/gamerson/liferay-blade-cli/compare/3649503~4...3649503) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
